### ISSUE TITLE
Bug in JsonDiff when handling multiple changes

### ISSUE THREAD

**Issue by dancadar** [espadrine/json-diff#1]
There is a bug in JsonDiff when comparing 2 jsons with more than a few changes (more than 6) which causes a memory leak (and crash due to insufficient memory)

using HashDiff to compare the same 2 jsons works as expected

**Comment by espadrine** [comment]
Thanks for reporting this issue! However, I believe I am missing some information. Could you provide me with the old and the new value?

For instance,

``` ruby
JsonDiff.diff({a:'a', b:'b', c:'c', d:'d', e:'e', f:'f', g:'g'},
              {a:'b', b:'c', c:'d', d:'e', e:'f', f:'g', g:'a'})
```

has size 7 and does not have a memory leak.

**Comment by espadrine** [comment]
Could you try using version 0.3.2 and trying again? I might have fixed it by correcting a seemingly unrelated bug.

**Comment by james2m** [comment]
@espadrine I can reproduce this. I am seeing the problem with large, nested hash / array combinations. If I diff them one way I get a successful result, if I reverse them I get an endless loop. 
[Reproduce endless loop in JsonDiff](https://gist.github.com/james2m/2c40240f0197471c04ebdf3ac9aeb460)

I've broken this down into convenient files so you can see the different data, and the results of diffing them. Hope this is helpful.

**Comment by espadrine** [comment]
@james2m Thanks a lot for the test case, it helped. This is now fixed.

**Comment by james2m** [comment]
@espadrine thanks for the update. Glad I could help.
